install.packages("smbinning")
library(ISLR)
library(caret)
library(ggplot2)
library(leaps)
library(pROC)
library(dplyr)
search()
college = na.omit(College)
names(college)
head(college)
str(college)
summary(college)
table(college$Private)
head(arrange(College, Enroll))
tail(arrange(College, Enroll))
ggplot(college, aes(Apps, Enroll)) +geom_point()
ggplot(college, aes(Private, Enroll)) + geom_boxplot()
par(mfrow=c(1,2))
hist(college$Accept,main="Applications accepted at the universities",col="green",breaks=30)
hist(college$Enroll,main="Students that are enrolled",col="blue",bin=40)
attach(college)
qplot(x=Apps, y=Enroll, color=Private, shape=Private, geom='point')+scale_shape(solid = FALSE)
#pairs(college[,1:10])
plot(Outstate ~ Private, data = college, col =c("green", "blue"))
set.seed(800)
trainIndex <- createDataPartition(college$Apps, p = 0.7, list = FALSE, times = 1)
caret_train <- college[ trainIndex,]
caret_test <- college[-trainIndex,]
summary(caret_train)
summary(caret_test)
model1<-glm(Private~.,data=caret_train, family= binomial(link="logit"))
summary(model1)
coef(model1)
exp(coef(model1))
model2<-glm(Private~ F.Undergrad+Outstate,data=caret_train, family= binomial(link="logit"))
summary(model2)
predication_train<- predict(model2, newdata = caret_train, type="response")
predicited.classes.min <-as.factor(ifelse(predication_train>=0.5, "Yes","No"))
confusionMatrix(predicited.classes.min, caret_train$Private, positive ='Yes')
##############################
predication_test<- predict(model2, newdata = caret_test, type="response")
predicited.classes.min <-as.factor(ifelse(predication_test>=0.5, "Yes","No"))
confusionMatrix(predicited.classes.min, caret_test$Private, positive ='Yes')
ROC_curve<- roc(caret_test$Private, predication_test)
plot(ROC_curve, col="red", ylab="TP rate", xlab="FP rate ")
area_under_curve<-auc(ROC_curve)
auc
detach(college)
rm(college)
